# Generated by Django 6.0.1 on 2026-01-29 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vault_path', models.CharField(max_length=500)),
                ('ai_confidence_score', models.FloatField()),
                ('is_altered', models.BooleanField(default=False)),
                ('rsa_signature', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
